### ISSUE TITLE
Issues with 1.17 for player expansion

### ISSUE THREAD

**Issue by CloudeLecaw** [PlaceholderAPI/Player-Expansion#52]
i thing this also effects other placeholders of this expansion in my case its the ping one

```
[22:35:51] [Craft Scheduler Thread - 88/WARN]: java.lang.NoSuchFieldException: ping
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at com.extendedclip.papi.expansion.player.PlayerUtil$1.cacheReflection(PlayerUtil.java:88)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:61)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:95)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:345)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:294)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:586)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:451)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:777)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[22:35:51] [Craft Scheduler Thread - 88/WARN]:  at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by darbyjack** [comment]
Development jars with the fix are provided in the Discord. 

Direct Download: https://cdn.discordapp.com/attachments/852317810394267708/853357598292443147/PAPI-Expansion-Player.jar

**Comment by CloudeLecaw** [comment]
Well the point just might be on spigots page   dont see the discord link.
Else inwould ask and take a look there in first case :)
