### ISSUE TITLE
Update 1.17

### ISSUE THREAD

**Issue by ErythroCraft** [PlaceholderAPI/Player-Expansion#53]
Hi.

Have an bug after install the expansion: player on my 1.17 server
Console output

[18:33:35] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: mvdw
[18:33:35] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player
[18:33:35] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer
[18:33:35] [Server thread/WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
[18:33:35] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[18:33:35] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[18:33:35] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[18:33:35] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[18:33:35] [Server thread/WARN]:        at com.extendedclip.papi.expansion.server.ServerExpansion.<init>(ServerExpansion.java:64)
[18:33:35] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:33:35] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[18:33:35] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:33:35] [Server thread/WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:33:35] [Server thread/WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:33:35] [Server thread/WARN]:        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:336)
[18:33:35] [Server thread/WARN]:        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:138)
[18:33:35] [Server thread/WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[18:33:35] [Server thread/WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[18:33:35] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[18:33:35] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[18:33:35] [Server thread/WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[18:33:35] [Server thread/WARN]:        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:257)
[18:33:35] [Server thread/WARN]:        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
[18:33:35] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[18:33:35] [Server thread/WARN]:        at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
[18:33:35] [Server thread/WARN]:        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$2(LocalExpansionManager.java:288)
[18:33:35] [Server thread/WARN]:        at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46)
[18:33:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
[18:33:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[18:33:35] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252)
[18:33:35] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436)
[18:33:35] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200)
[18:33:35] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027)
[18:33:35] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[18:33:35] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by darbyjack** [comment]
Is this happening in the latest dev build posted in the discord?

**Comment by ErythroCraft** [comment]
The dev build of PAPI, expansion: player and expansion: server works fine.

[18:48:59] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player
[18:48:59] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server
[18:48:59] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: servertime

sp thx
