### ISSUE TITLE
I have this error with the variable %player_locale_display_country%

### ISSUE THREAD

**Issue by frogglen** [PlaceholderAPI/Player-Expansion#68]
```
[22:22:33 WARN]: java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "localeStr" is null
[22:22:33 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:200)
[22:22:33 WARN]:        at PlaceholderAPI-2.11.3-DEV-160.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[22:22:33 WARN]:        at PlaceholderAPI-2.11.3-DEV-160.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[22:22:33 WARN]:        at PlaceholderAPI-2.11.3-DEV-160.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[22:22:33 WARN]:        at InteractiveChat-4.2.3.8.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:104)
[22:22:33 WARN]:        at InteractiveChat-4.2.3.8.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:83)
[22:22:33 WARN]:        at InteractiveChat-4.2.3.8.jar//com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:104)
[22:22:33 WARN]:        at InteractiveChat-4.2.3.8.jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:85)
[22:22:33 WARN]:        at InteractiveChat-4.2.3.8.jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:530)
[22:22:33 WARN]:        at InteractiveChat-4.2.3.8.jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$200(OutMessagePacket.java:83)
[22:22:33 WARN]:        at InteractiveChat-4.2.3.8.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:415)
[22:22:33 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[22:22:33 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:22:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:22:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:22:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Fuglen** [comment]
I had the same issue and downgraded Paper from 1.20.2 to 1.20.1 and that solved it, looking forward for an update or better solution.
