### ISSUE TITLE
Console Warning Messages

### ISSUE THREAD

**Issue by BboyZeroOne** [PlaceholderAPI/Player-Expansion#78]
I'm not sure if this issue is related to this expansion, but it has been bugging me a while.

[01:01:53 WARN]: java.lang.NoSuchFieldException: ping
[01:01:53 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[01:01:53 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:46)
[01:01:53 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:298)
[01:01:53 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[01:01:53 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[01:01:53 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:104)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:83)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:104)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:85)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:598)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$200(OutMessagePacket.java:84)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:483)
[01:01:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[01:01:53 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[01:01:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:01:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:01:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:01:53 WARN]: java.lang.NoSuchFieldException: ping
[01:01:53 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[01:01:53 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:46)
[01:01:53 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:300)
[01:01:53 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[01:01:53 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[01:01:53 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:104)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:83)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:104)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:85)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.processPacket(OutMessagePacket.java:598)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket.access$200(OutMessagePacket.java:84)
[01:01:53 WARN]:        at InteractiveChat-4.2.6.0.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.lambda$onPacketSending$0(OutMessagePacket.java:483)
[01:01:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[01:01:53 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[01:01:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:01:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:01:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by iGabyTM** [comment]
Update the expansion
